version: '3.9'

services:
  server-node:
    build: .
    container_name: blocksui-server-node
    image: blocksui-server-node
    volumes:
      - ".:/go/src"
      - "../cache:/tmp/cache"
    environment:
      ENV: development
      ACCESS_TOKEN: ${GITHUB_TOKEN}
