---
AWSTemplateFormatVersion: '2010-09-09'

Description: CRCLS decentralized node infrastructure to support crcls.xyz

Parameters:
  ImageTag:
    Description: ARN for the node container in ECR
    Type: String
  DomainName:
    Default: 'crcls.xyz'
    Description: The FQDN for this website
    Type: String
  Subdomain:
    Default: '*'
    Description: The Subdomain for the chosen domain
    Type: String
  MaxTaskCount:
    Default: 20
    Description: Maximim amount of node tasks to run
    Type: String
  MinTaskCount:
    Default: 2
    Description: Minimum amount of node tasks to run
    Type: String

Resources:
  VPC:
    Description: Create the VPC for CRCLS app
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://crcls-app.s3.${AWS::Region}.amazonaws.com/infra/vpc.yml'

  NodeCluster:
    Description: Create the ECS cluster, service, and tasks
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ContainerName: crcls-node
        Image: !Sub '288140218613.dkr.ecr.${AWS::Region}.amazonaws.com/crcls-node:${ImageTag}'
        MaxTaskCount: !Ref MaxTaskCount
        MinTaskCount: !Ref MinTaskCount
        SecurityGroup: !GetAtt VPC.Outputs.NodeSecurityGroup
        EFSSecurityGroup: !GetAtt VPC.Outputs.MountTargetSecurityGroup
        Subnets: !Join
          - ','
          - - !GetAtt VPC.Outputs.PublicSubnet0
            - !GetAtt VPC.Outputs.PublicSubnet1
        VpcId: !GetAtt VPC.Outputs.VpcId
      TemplateURL: !Sub 'https://crcls-node.s3.${AWS::Region}.amazonaws.com/infra/node_cluster.yml'

  # ------------------
  # CloudFront config

  CachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        DefaultTTL: 86400
        MaxTTL: 86400
        MinTTL: 86400
        Name: CRCLS-App-Node-Cache-Policy
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingGzip: true
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: all

  OriginRequestPolicy:
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties:
      OriginRequestPolicyConfig:
        CookiesConfig:
          CookieBehavior: none
        HeadersConfig:
          HeaderBehavior: allViewer
        Name: CRCLS-OriginReqPolicy
        QueryStringsConfig:
          QueryStringBehavior: all

  ResponseHeadersPolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        CorsConfig:
          AccessControlAllowCredentials: true
          AccessControlAllowHeaders:
            Items:
              - 'Origin'
              - 'X-Requested-With'
              - 'Content-Type'
              - 'Accept'
          AccessControlAllowMethods:
            Items:
              - 'POST'
          AccessControlAllowOrigins:
            Items:
              - '*'
          OriginOverride: false
        Name: crcls-app-response-headers-policy

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
          - !Sub '${Subdomain}.${DomainName}'
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - PATCH
            - POST
            - DELETE
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachePolicyId: !Ref CachePolicy
          Compress: true
          DefaultTTL: 86400
          MaxTTL: 31536000
          OriginRequestPolicyId: !Ref OriginRequestPolicy
          ResponseHeadersPolicyId: !Ref ResponseHeadersPolicy
          TargetOriginId: !GetAtt NodeCluster.Outputs.AlbArn
          ViewerProtocolPolicy: 'redirect-to-https'
        Enabled: true
        HttpVersion: 'http2'
        DefaultRootObject: 'index.html'
        IPV6Enabled: true
        Logging:
          Bucket: !ImportValue 's3-crcls-logs-domain'
          Prefix: !Sub 'app/cdn'
        Origins:
          - CustomOriginConfig:
              OriginProtocolPolicy: http-only
            DomainName: !GetAtt NodeCluster.Outputs.AlbDomain
            Id: !GetAtt NodeCluster.Outputs.AlbArn
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: 'arn:aws:acm:us-east-1:288140218613:certificate/bcd2f715-2dfa-4c40-8a59-223fb4065032'
          MinimumProtocolVersion: 'TLSv1.2_2018'
          SslSupportMethod: 'sni-only'

  Route53ARecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        EvaluateTargetHealth: false
        # The  following HosteZoneId is always used for alias records pointing to CF.
        HostedZoneId: 'Z2FDTNDATAQYW2'
      HostedZoneName: !Sub '${DomainName}.'
      Name: !Ref DomainName
      Type: 'A'

Outputs:
  CloudFrontDistributionId:
    Value: !Ref CloudFrontDistribution
  CloudFrontDistributionDomain:
    Description: CloudFront distribution domain
    Value: !GetAtt CloudFrontDistribution.DomainName
