version: '3.9'

services:
  server-node:
    build:
      context: .
      dockerfile: ./docker/dev.Dockerfile
    container_name: blocksui-node-dev
    image: blocksui-node
    ports:
      - '8081:80'
      - '5001:5001'
    environment:
      CHAIN_NAME: ${CHAIN_NAME}
      CONTRACTS_CID: ${CONTRACTS_CID}
      NETWORK_NAME: ${NETWORK_NAME}
      PRIMITIVES_CID: ${PRIMITIVES_CID}
      PROVIDER_URL: ${PROVIDER_URL}
      RECOVERY_PHRASE: ${RECOVERY_PHRASE}
      WEB3STORAGE_TOKEN: ${WEB3STORAGE_TOKEN}
      ENV: development
      ACCESS_TOKEN: ${GITHUB_TOKEN}
    volumes:
      - '.:/go/src'
