version: '3.9'

services:
  server-node:
    build:
      context: .
      dockerfile: ./docker/aws.Dockerfile
    container_name: blocksui-node-aws
    image: blocksui-node
    ports:
      - '8081:80'
    environment:
      BLOCK_NFT_CID: 0
      PRIMITIVES_CID: ${PRIMITIVES_CID}
      PROVIDER_URL: ${PROVIDER_URL}
      RECOVERY_PHRASE: ${RECOVERY_PHRASE}
      STAKING_CID: ${STAKING_CID}
      WEB3STORAGE_TOKEN: ${WEB3STORAGE_TOKEN}
      ENV: development
      ACCESS_TOKEN: ${GITHUB_TOKEN}

